### PR TITLE
Merge histories with Cornelius's Hyper fork

### PR DESCRIPTION
**Pull request by philip-peterson**

### CODE REVIEW

**Comment by philip-peterson** [comment]
(Not merging these without @corneliusroemer 's approval)

**Comment by corneliusroemer** [comment]
Sorry for the delay here, feel free to merge! I give you full approval/permission!

**Comment by philip-peterson** [comment]
@corneliusroemer Awesome, thank you. By the way, did not mean to close out that PR that was sent to your fork. I've been battling some issues with CodeQL scans and have had to multiple times delete and/or rename the canary branch to get around branch protection rules. Will re-open when it's more stable!

**Comment by philip-peterson** [comment]
Moving these changes to #76 because I can't resolve merge conflicts here since I wouldn't be able to push them to a non-Quine repo.

**Pull request closed without merging**
