### PR TITLE
Merge histories with @corneliusroemer's Hyper fork

### PR DESCRIPTION
**Pull request by philip-peterson**

### CODE REVIEW

**Comment by philip-peterson** [comment]
@corneliusroemer I guess they can't be merged because of the restriction that all commits be signed. Did you turn that off on your fork?

**Comment by corneliusroemer** [comment]
What can't be merged? The conflicts?

**Comment by philip-peterson** [comment]
@corneliusroemer Sorry, the conflicts appeared after I left that comment. Those are manageable, but the other issue is the commits in this branch authored by you are not signed (contrast with Dependabot's commits which are signed and display the green "verified" badge; in order to merge all commits must have the green verified badge):

Screenshot 2024-11-22 at 7 28 48 PM

**Comment by philip-peterson** [comment]
I think I can always sign them myself. But in case you want to sign your own commits, these were the instructions I followed, fairly simple process, just about configuring a gpg agent and git to work together on your local machine: https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification#gpg-commit-signature-verification

**Comment by philip-peterson** [comment]
@corneliusroemer I ended up having to rebase and make some slight conflict resolutions as well as sign the commits. But the changes you made will be very helpful, thanks!

**Pull request merged**
